# -*- coding: utf-8 -*-
"""20230913_A120E103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1arTRuaimi866_1dPu1smLKWFs4woehY2
"""

3**23